app_prueba/config/routes.rb
Rails.application.routes.draw do
  resources :articulos do
    resources :comentarios
  end
  root 'bienvenido#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app_prueba/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app_prueba/app/models/articulo.rb
class Articulo < ActiveRecord::Base
  has_many :comentarios, dependent: :destroy
  validates :titular, presence: true,
                    length: { minimum: 5 }
end

app_prueba/app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :articulo
end

app_prueba/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app_prueba/app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
# http_basic_authenticate_with name: "dhh", password: "secreto", except: [:index, :show]
 
  def index
    @articulos = Articulo.all
  end
 
  def show
    @articulo = Articulo.find(params[:id])
  end
 
  def new
    @articulo = Articulo.new
  end
 
  def edit
    @articulo = Articulo.find(params[:id])
  end
 
  def create
    @articulo = Articulo.new(articulo_params)
 
    if @articulo.save
      redirect_to @articulo
    else
      render 'new'
    end
  end
 
  def update
    @articulo = Articulo.find(params[:id])
 
    if @articulo.update(articulo_params)
      redirect_to @articulo
    else
      render 'edit'
    end
  end
 
  def destroy
    @articulo = Articulo.find(params[:id])
    @articulo.destroy
 
    redirect_to articulos_path
  end
 
  private
    def articulo_params
      params.require(:articulo).permit(:titular, :contenido)
    end
end

app_prueba/app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app_prueba/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
   # http_basic_authenticate_with name: "dhh", password: "secreto", only: :destroy
  def create
    @articulo = Articulo.find(params[:articulo_id])
    @comentario = @articulo.comentarios.create(comentario_params)
    redirect_to articulo_path(@articulo)
  end
 
  def destroy
    @articulo = Articulo.find(params[:articulo_id])
    @comentario = @articulo.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to articulo_path(@articulo)
  end
 
  private
    def comentario_params
      params.require(:comentario).permit(:comentarista, :contenido)
    end
end

app_prueba/app/helpers/application_helper.rb
module ApplicationHelper
end

app_prueba/app/helpers/articulos_helper.rb
module ArticulosHelper
end

app_prueba/app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app_prueba/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app_prueba/app/views/articulos/_form.html.erb
<%= form_for @articulo do |f| %>
 
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@articulo.errors.count, "error") %> han impedido que el artículo sea grabado:
      </h2>
      <ul>
        <% @articulo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :titular %><br>
    <%= f.text_field :titular %>
  </p>
 
  <p>
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </p>
 
  <p>
    <%= f.submit 'Guardar Artículo' %>
  </p>
 
<% end %>

app_prueba/app/views/articulos/edit.html.erb
<h1>Editar el artículo</h1>
 
<%= render 'form' %>
 
<%= link_to 'Volver', articulos_path %>

app_prueba/app/views/articulos/index.html.erb
<h1>Listando Artículos</h1>
<%= link_to 'Nuevo artículo', new_articulo_path %>
<table>
  <tr>
    <th>Titular</th>
    <th>Contenido</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articulos.each do |articulo| %>
    <tr>
      <td><%= articulo.titular %></td>
      <td><%= articulo.contenido %></td>
      <td><%= link_to 'Ver', articulo_path(articulo) %></td>
      <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
      <td><%= link_to 'Borrar', articulo_path(articulo),
              method: :delete,
              data: { confirm: '¿Estás seguro?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Crear Artículo', new_articulo_path %>

app_prueba/app/views/articulos/new.html.erb
<h1>Editar el artículo</h1>
 
<%= render 'form' %>
 
<%= link_to 'Volver', articulos_path %>

app_prueba/app/views/articulos/show.html.erb
<p>
  <strong>Titular:</strong>
  <%= @articulo.titular %>
</p>
 
<p>
  <strong>Contenido:</strong>
  <%= @articulo.contenido %>
</p>
 
<h2>Comentarios</h2>
<%= render @articulo.comentarios %>
 
<h2>Añade un comentario:</h2>
<%= render 'comentarios/form' %>
 
<%= link_to 'Editar Artículo', edit_articulo_path(@articulo) %> |
<%= link_to 'Volver a Articulos', articulos_path %>

app_prueba/app/views/bienvenido/index.html.erb
<h1>¡Hola, Rails!</h1>
<%= link_to 'Application New', controller: 'articulos' %>