rails_all_party/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root 'partys#index'
  get     '/signup',   to:  'users#new'
  get    'packages'  => 'packages#index'
  get     '/login',    to:  'sessions#new'
  post    '/login',    to:  'sessions#create'
  delete  '/logout',   to:  'sessions#destroy'
  resources :partys
  resources :packages do
    resources :tickets
  end
  resources :users 
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

rails_all_party/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllParty</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>

<body>
    <nav class=" nav-nav">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to "Inicio",{ controller: "partys", action: "index" }, class: "link_nav" %></li>
          <li><%= link_to "Paquetes", { controller: "packages", action: "index" }, class: "link_nav" %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
           <li><%= link_to "Carrito",  '#', :class=>"linki" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cuenta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user, :class=>"linki" %></li>
              <li><%= link_to "Actualizar", edit_user_path(current_user), :class=>"linki"%></li>
              <li><%= link_to "Salir", logout_path, method: "delete", :class=>"linki" %></li>
            </ul>
          </li>
        <% else %>        
          <li><%= link_to "Entrar",  login_path , :class=>"linki" %></li>
          <li><%= link_to "Registrarse", signup_path, :class=>"linki" %></li>
        <% end %>
      </div>
    </nav>
    <p class = "notice"><%= notice %>
    <p class= = "alert"><%= alert %>
    <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div> 
    <%= yield %>
  </body>
</html>